-- UJRIS Lite v3.0.0 - Initial Migration
-- This migration is auto-generated by Prisma. Run: prisma migrate dev --name init

-- CreateEnum
CREATE TYPE "CaseStatus" AS ENUM ('INTAKE', 'EVIDENCE_PENDING', 'GENERATING', 'ACTIVE', 'RESOLVED', 'CLOSED', 'REFUND_REQUESTED', 'REFUNDED');

-- CreateEnum
CREATE TYPE "RefundStatus" AS ENUM ('NONE', 'PENDING', 'APPROVED', 'REJECTED', 'PROCESSED');

-- CreateEnum
CREATE TYPE "EvidenceType" AS ENUM ('DOCUMENT', 'IMAGE', 'PDF', 'TEXT', 'OTHER');

-- CreateEnum
CREATE TYPE "DecisionType" AS ENUM ('APPEAL', 'COMPLAINT', 'DISPUTE', 'TRIBUNAL', 'ARBITRATION', 'MEDIATION', 'FORMAL_GRIEVANCE', 'OTHER');

-- CreateEnum
CREATE TYPE "GroundsType" AS ENUM ('DISCRIMINATION', 'BREACH_OF_CONTRACT', 'UNFAIR_DISMISSAL', 'NEGLIGENCE', 'PROCEDURAL_IRREGULARITY', 'HUMAN_RIGHTS_VIOLATION', 'CONSUMER_RIGHTS', 'DATA_PROTECTION', 'OTHER');

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'user',
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AuthToken" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "revokedAt" TIMESTAMP(3),

    CONSTRAINT "AuthToken_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Case" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "status" "CaseStatus" NOT NULL DEFAULT 'INTAKE',
    "refundStatus" "RefundStatus" NOT NULL DEFAULT 'NONE',
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "decisionType" "DecisionType" NOT NULL DEFAULT 'OTHER',
    "grounds" "GroundsType" NOT NULL DEFAULT 'OTHER',
    "desiredOutcome" TEXT,
    "jurisdiction" TEXT,
    "opposingParty" TEXT,
    "incidentDate" TIMESTAMP(3),
    "submissionDeadline" TIMESTAMP(3),
    "intakeData" JSONB,
    "nextQuestions" JSONB,
    "intakeComplete" BOOLEAN NOT NULL DEFAULT false,
    "caseDocument" TEXT,
    "executiveSummary" TEXT,
    "legalArguments" JSONB,
    "recommendedActions" JSONB,
    "strengthScore" INTEGER,
    "riskAssessment" TEXT,
    "generatedAt" TIMESTAMP(3),
    "evidenceSummary" TEXT,
    "evidenceSummaryAt" TIMESTAMP(3),
    "refundReason" TEXT,
    "refundRequestedAt" TIMESTAMP(3),
    "refundApprovedAt" TIMESTAMP(3),
    "refundProcessedAt" TIMESTAMP(3),
    "refundAmount" DOUBLE PRECISION,
    "refundAmountCurrency" TEXT DEFAULT 'GBP',
    "refundEligible" BOOLEAN,
    "refundNotes" TEXT,
    "aiModel" TEXT,
    "aiTokensUsed" INTEGER,
    "processingTimeMs" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Case_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Evidence" (
    "id" TEXT NOT NULL,
    "caseId" TEXT NOT NULL,
    "type" "EvidenceType" NOT NULL DEFAULT 'DOCUMENT',
    "fileName" TEXT NOT NULL,
    "originalName" TEXT NOT NULL,
    "mimeType" TEXT NOT NULL,
    "sizeBytes" INTEGER NOT NULL,
    "storageKey" TEXT NOT NULL,
    "sha256Hash" TEXT NOT NULL,
    "extractedText" TEXT,
    "summary" TEXT,
    "metadata" JSONB,
    "uploadedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "processedAt" TIMESTAMP(3),

    CONSTRAINT "Evidence_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RefundRequest" (
    "id" TEXT NOT NULL,
    "caseId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "status" "RefundStatus" NOT NULL DEFAULT 'PENDING',
    "reason" TEXT NOT NULL,
    "requestedAmount" DOUBLE PRECISION NOT NULL,
    "approvedAmount" DOUBLE PRECISION,
    "currency" TEXT NOT NULL DEFAULT 'GBP',
    "adminNotes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "processedAt" TIMESTAMP(3),

    CONSTRAINT "RefundRequest_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AuditLog" (
    "id" TEXT NOT NULL,
    "caseId" TEXT,
    "userId" TEXT,
    "action" TEXT NOT NULL,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT,
    "oldValues" JSONB,
    "newValues" JSONB,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "adminKey" BOOLEAN NOT NULL DEFAULT false,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SystemConfig" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "description" TEXT,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "updatedBy" TEXT,

    CONSTRAINT "SystemConfig_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE INDEX "User_email_idx" ON "User"("email");
CREATE UNIQUE INDEX "AuthToken_token_key" ON "AuthToken"("token");
CREATE INDEX "AuthToken_token_idx" ON "AuthToken"("token");
CREATE INDEX "AuthToken_userId_idx" ON "AuthToken"("userId");
CREATE INDEX "Case_userId_idx" ON "Case"("userId");
CREATE INDEX "Case_status_idx" ON "Case"("status");
CREATE INDEX "Case_refundStatus_idx" ON "Case"("refundStatus");
CREATE INDEX "Case_createdAt_idx" ON "Case"("createdAt");
CREATE UNIQUE INDEX "Evidence_storageKey_key" ON "Evidence"("storageKey");
CREATE INDEX "Evidence_caseId_idx" ON "Evidence"("caseId");
CREATE INDEX "Evidence_sha256Hash_idx" ON "Evidence"("sha256Hash");
CREATE INDEX "RefundRequest_caseId_idx" ON "RefundRequest"("caseId");
CREATE INDEX "RefundRequest_status_idx" ON "RefundRequest"("status");
CREATE INDEX "AuditLog_caseId_idx" ON "AuditLog"("caseId");
CREATE INDEX "AuditLog_userId_idx" ON "AuditLog"("userId");
CREATE INDEX "AuditLog_action_idx" ON "AuditLog"("action");
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");
CREATE UNIQUE INDEX "SystemConfig_key_key" ON "SystemConfig"("key");
CREATE INDEX "SystemConfig_key_idx" ON "SystemConfig"("key");

-- AddForeignKey
ALTER TABLE "AuthToken" ADD CONSTRAINT "AuthToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Case" ADD CONSTRAINT "Case_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Evidence" ADD CONSTRAINT "Evidence_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "Case"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RefundRequest" ADD CONSTRAINT "RefundRequest_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "Case"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_caseId_fkey" FOREIGN KEY ("caseId") REFERENCES "Case"("id") ON DELETE SET NULL ON UPDATE CASCADE;
